// import-graph.mjs — generate the real import graph of the mona packages.
//
// Reads every import edge from source (apps/desktop, packages/engine,
// packages/control-plane), collapses them to package-level edges, and
// prints the diagram into the GENERATED block of docs/ARCHITECTURE.md.
// The docs can never drift from reality: this script reads the code.
//
//   node scripts/import-graph.mjs

import { readFileSync, readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..');

const PACKAGES = [
  { id: 'apps/desktop', dir: join(ROOT, 'apps', 'desktop'), label: 'apps/desktop (device agent)' },
  { id: 'packages/engine', dir: join(ROOT, 'packages', 'engine'), label: 'packages/engine (device core)' },
  { id: 'packages/control-plane', dir: join(ROOT, 'packages', 'control-plane'), label: 'packages/control-plane (server library)' },
];

function walk(dir, out = []) {
  for (const e of readdirSync(dir)) {
    if (e === 'node_modules' || e.startsWith('.')) continue;
    const p = join(dir, e);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(m?js)$/.test(e)) out.push(p);
  }
  return out;
}

const ownerOf = (file) => PACKAGES.find((p) => file.startsWith(p.dir + '/'))?.id || null;

function packageOf(importee, spec) {
  if (spec.startsWith('@mona/')) {
    const name = spec.split('/').slice(0, 2).join('/');
    if (name === '@mona/engine') return 'packages/engine';
    if (name === '@mona/control-plane') return 'packages/control-plane';
    if (name === '@mona/protocol') return 'packages/protocol';
    return null; // external dependency
  }
  if (!spec.startsWith('.')) return null; // node: builtin or external
  // resolve relative spec against the importee file
  const target = join(importee.replace(/[^/]+$/, ''), spec);
  return ownerOf(target);
}

const edges = new Map(); // "from -> to" -> count
for (const pkg of PACKAGES) {
  for (const file of walk(pkg.dir)) {
    const src = readFileSync(file, 'utf8');
    for (const m of src.matchAll(/import\s*(?:[^'"]*?from\s*)?['"]([^'"]+)['"]/g)) {
      const to = packageOf(file, m[1]);
      if (!to) continue;
      const from = ownerOf(file);
      const key = `${from} -> ${to}`;
      edges.set(key, (edges.get(key) || 0) + 1);
    }
  }
}

const mermaid = ['flowchart LR'];
for (const [edge, count] of [...edges.entries()].sort()) {
  const [a, b] = edge.split(' -> ');
  const la = PACKAGES.find((p) => p.id === a)?.label || a;
  const lb = PACKAGES.find((p) => p.id === b)?.label || b;
  mermaid.push(`    ${JSON.stringify(la)} -->|"${count} import${count > 1 ? 's' : ''}"| ${JSON.stringify(lb)}`);
}

const MARK = '<!-- GENERATED BY scripts/import-graph.mjs — DO NOT EDIT BETWEEN THE MARKERS -->';
const archPath = join(ROOT, 'docs', 'ARCHITECTURE.md');
let arch = readFileSync(archPath, 'utf8');
const start = arch.indexOf(MARK);
const end = arch.indexOf(MARK, start + MARK.length);
const block = `${MARK}\n\nReal import edges, read from the source (${edges.size} package-level edge${edges.size === 1 ? '' : 's'}):\n\n\`\`\`mermaid\n${mermaid.join('\n')}\n\`\`\`\n\n${MARK}`;
if (start !== -1 && end !== -1) {
  arch = arch.slice(0, start) + block + arch.slice(end + MARK.length);
} else {
  arch = arch.trimEnd() + '\n\n' + block + '\n';
}
writeFileSync(archPath, arch);

console.log(`import-graph: ${edges.size} package-level edges`);
for (const [edge, count] of [...edges.entries()].sort()) console.log(`  ${edge} (${count})`);
console.log(`wrote ${relative(ROOT, archPath)}`);
